import type { Metadata } from "next";
import { Poltawski_Nowy } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

// Load Poltawski Nowy
const poltawskiNowy = Poltawski_Nowy({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poltawskiNowy.className} antialiased min-h-[100rem] flex flex-col`}
      >
        <Header />
        <main className="flex-grow mb-[5rem]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
